window.APLUS_WIKI_CONTENT = {
  "generated_at": "2026-05-06T14:30:02.315Z",
  "source_csv": "datasets/course-sequence-map.csv",
  "pages": [
    {
      "order": 1,
      "sequence_id": "CS-001",
      "group": "Intro",
      "topic": "Intro",
      "slug": "intro",
      "material_path": "materials/course-sequence/intro.md",
      "comptia_area": "Core 2 expansion placeholder",
      "route_id": "MAP-006",
      "app_module": "symptoms",
      "practice_action": "Match Safe Checks",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Intro\n\n## What\n\nThis page is the front door to the A+ Visual Lab course-sequence wiki.\n\nThe course path is a reading route, not a replacement for hands-on practice. Each topic gives the learner a short explanation, a few support clues, source links, and a nearby app activity.\n\n## Why\n\nA+ study can feel wide: hardware, mobile devices, networking, virtualization, cloud, troubleshooting, operating systems, security, and procedures all appear across the two exams. This project keeps the first pass calmer by letting the learner choose one topic, read a short page, then practice one visible task.\n\n## How\n\nUse this rhythm:\n\n1. Pick one course topic.\n2. Read the short wiki page.\n3. Open the matching practice module.\n4. Capture one sentence of evidence.\n5. Move on or stop before overload.\n\n```mermaid\nflowchart LR\n  Map[\"Start Map\"] --> Read[\"Read one topic\"]\n  Read --> Practice[\"Practice one activity\"]\n  Practice --> Evidence[\"Capture evidence\"]\n  Evidence --> Review[\"Review progress\"]\n  Review --> Map\n```\n\nPractice\n\n- [Open Match Safe Checks](../../app/index.html#module=symptoms)\n- [Open Start Map](../../app/index.html#module=start)\n\nSources:\n\n- [CompTIA A+ Core 1 and 2 V15](https://www.comptia.org/en-us/certifications/a/core-1-and-2-v15/)\n- [CompTIA A+ 220-1201 exam objectives PDF](https://partners.comptia.org/docs/default-source/resources/comptia-a-220-1201-exam-objectives-%282-0%29.pdf)\n\nChecklist:\n\n- [x] Explain the purpose of the material repo.\n- [x] Keep the learner path short.\n- [x] Link the relevant app modules.\n- [x] Add a simple topic overview diagram.\n"
    },
    {
      "order": 2,
      "sequence_id": "CS-002",
      "group": "Hardware sequence",
      "topic": "Cable types",
      "slug": "cable-types",
      "material_path": "materials/course-sequence/cable-types.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Cable Types\n\n## What\n\nCable types are the physical connectors and leads used to move data, video, and power.\n\nFor this project, the learner is mainly learning to tell common shapes apart: RJ45, USB-A, USB-C, HDMI, and Thunderbolt over USB-C.\n\n## Why\n\nCable recognition is one of the fastest wins in A+ study.\n\nIf the learner can identify the connector shape quickly, the rest of the troubleshooting flow becomes easier.\n\n## How\n\n- Learn the shape first.\n- Learn the purpose second.\n- Match the cable to the port before worrying about speed tiers or marketing labels.\n\nNotes:\n\n- USB Type-C is the connector shape, not the same thing as every protocol that can use it.\n- Thunderbolt uses the USB-C shape on many devices, but not every USB-C port is Thunderbolt.\n- HDMI is the standard display connector in this set.\n\nSources:\n\n- USB-IF Type-C guidelines on reversible plug orientation and cable direction: [USB Type-C cable and connector guidelines](https://www.usb.org/sites/default/files/usb_type-c_language_product_and_packaging_guidelines_20230320.pdf)\n- Intel overview of Thunderbolt over USB-C: [Thunderbolt Technology](https://www.intel.com/content/www/us/en/architecture-and-technology/thunderbolt/overview.html)\n- HDMI overview and cable resources: [HDMI Specifications and Programs](https://www.hdmi.org/spec/index)\n\nChecklist:\n\n- [x] Create the cable-types page shell.\n- [ ] Add a visual shape comparison.\n- [ ] Add a short learner example.\n- [x] Link the cable matching lab.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 3,
      "sequence_id": "CS-003",
      "group": "Hardware sequence",
      "topic": "Motherboards",
      "slug": "motherboards",
      "material_path": "materials/course-sequence/motherboards.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Motherboards\n\n## What\n\nA motherboard is the main circuit board in a PC or laptop.\n\nIt is the place where the processor, memory, storage connectors, power delivery, firmware, and expansion paths meet.\n\n## Why\n\nMotherboards matter because many A+ questions are really about finding where a part connects or what role a slot plays.\n\nOnce the learner can read the board, they can reason about upgrades and common faults more confidently.\n\n## How\n\n- Start with board layout.\n- Find the CPU socket or soldered CPU area.\n- Find the memory slots.\n- Find storage connectors, power connectors, and front-panel or port headers.\n\nSources:\n\n- CompTIA A+ Core 1 public overview: [CompTIA A+ Core 1 (V15)](https://www.comptia.org/en/certifications/a/core-1-and-2-v15/)\n\nChecklist:\n\n- [x] Create the motherboards page shell.\n- [ ] Add a board-layout visual.\n- [ ] Add common slot and header labels.\n- [x] Link the hardware drill.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 4,
      "sequence_id": "CS-004",
      "group": "Hardware sequence",
      "topic": "Cooling and power",
      "slug": "cooling-and-power",
      "material_path": "materials/course-sequence/cooling-and-power.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Cooling And Power\n\n## What\n\nThis topic covers how a device stays powered and stays cool.\n\nIt includes power supplies, adapters, batteries, fans, heatsinks, and the basic idea that heat and power problems can look like many other faults.\n\n## Why\n\nCooling and power issues are common and easy to misread.\n\nIf a learner jumps too quickly to a deep fix, they can miss the safer first check.\n\n## How\n\n- Check whether the device powers on.\n- Confirm whether the charger, outlet, or battery path is working.\n- Look for fan noise, blocked vents, or obvious heat symptoms.\n- Treat the simplest visible cause first.\n\nSources:\n\n- CompTIA A+ Core 1 public overview: [CompTIA A+ Core 1 (V15)](https://www.comptia.org/en/certifications/a/core-1-and-2-v15/)\n\nChecklist:\n\n- [x] Create the cooling-and-power page shell.\n- [ ] Add a power-path diagram.\n- [ ] Add a fan and vent visual cue.\n- [x] Link the relevant troubleshooting activity.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 5,
      "sequence_id": "CS-005",
      "group": "Hardware sequence",
      "topic": "System memory",
      "slug": "system-memory",
      "material_path": "materials/course-sequence/system-memory.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# System Memory\n\n## What\n\nSystem memory is RAM.\n\nIt is the short-term workspace the computer uses while programs are running.\n\n## Why\n\nRAM is one of the easiest parts to identify in the lab, and it has a useful mental model: if the device is working slowly, memory is one of the things a learner should think about, but not blindly replace.\n\n## How\n\n- Describe RAM as working memory.\n- Show where RAM usually sits on the board.\n- Teach safe handling by the edges.\n- Connect the part to performance symptoms and upgrade choices.\n\nSources:\n\n- CompTIA A+ Core 1 public overview: [CompTIA A+ Core 1 (V15)](https://www.comptia.org/en/certifications/a/core-1-and-2-v15/)\n\nChecklist:\n\n- [x] Create the system-memory page shell.\n- [ ] Add a RAM-stick visual.\n- [ ] Add a safe-handling note.\n- [x] Link the laptop memory practice activity.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 6,
      "sequence_id": "CS-006",
      "group": "Hardware sequence",
      "topic": "BIOS/UEFI",
      "slug": "bios-uefi",
      "material_path": "materials/course-sequence/bios-uefi.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# BIOS/UEFI\n\n## What\n\nBIOS and UEFI are firmware layers that help start the computer before the operating system loads.\n\nUEFI is the modern replacement for legacy BIOS on most current devices.\n\n## Why\n\nThis topic helps the learner understand startup, boot mode, secure boot, and why newer systems usually behave differently from older ones.\n\n## How\n\n- Learn that firmware starts the machine before the OS.\n- Learn that UEFI is the current standard on modern systems.\n- Learn that some devices can still emulate BIOS behavior for compatibility.\n- Connect the boot mode to partition style and security behavior.\n\nSources:\n\n- Microsoft overview of UEFI as the successor to BIOS: [Windows deployment scenarios and tools](https://learn.microsoft.com/en-us/windows/deployment/windows-deployment-scenarios-and-tools)\n- Microsoft boot-mode guidance: [Boot to UEFI Mode or legacy BIOS mode](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/boot-to-uefi-mode-or-legacy-bios-mode?view=windows-11)\n\nChecklist:\n\n- [x] Create the BIOS-UEFI page shell.\n- [ ] Add a simple boot-flow diagram.\n- [ ] Add a BIOS versus UEFI comparison card.\n- [x] Link the startup practice activity.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 7,
      "sequence_id": "CS-007",
      "group": "Hardware sequence",
      "topic": "Storage device",
      "slug": "storage-device",
      "material_path": "materials/course-sequence/storage-device.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Storage Device\n\n## What\n\nStorage devices keep files and installed software after power is off.\n\nIn the course sequence, this covers SSDs, HDDs, SATA, and M.2-level concepts at the learner-friendly service level.\n\n## Why\n\nStorage is a common exam and lab topic because it connects physical parts to symptoms like slow startup, missing files, and boot problems.\n\n## How\n\n- Compare shape and connector style.\n- Explain where the device sits in the system.\n- Tie the part to common symptoms.\n- Keep the lesson focused on recognition and first-step troubleshooting.\n\nSources:\n\n- CompTIA A+ Core 1 public overview: [CompTIA A+ Core 1 (V15)](https://www.comptia.org/en/certifications/a/core-1-and-2-v15/)\n\nChecklist:\n\n- [x] Create the storage-device page shell.\n- [ ] Add a SATA-versus-M.2 visual.\n- [ ] Add a slow-startup symptom note.\n- [x] Link the storage comparison activity.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 8,
      "sequence_id": "CS-008",
      "group": "Virtualization and cloud sequence",
      "topic": "Virtualization concepts",
      "slug": "virtualization-concepts",
      "material_path": "materials/course-sequence/virtualization-concepts.md",
      "comptia_area": "Virtualization and Cloud Computing",
      "route_id": "MAP-003",
      "app_module": "flash",
      "practice_action": "Review Visual Cards",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Virtualization Concepts\n\n## What\n\nVirtualization means using software to create a computer inside a computer.\n\nThat virtual computer is usually called a virtual machine, or VM.\n\n## Why\n\nThis matters because A+ learners need to understand what a VM is, why it helps, and why it is not the same as a full physical machine.\n\nIt also helps explain labs, testing, and cloud services without requiring a physical server room.\n\n## How\n\n- A host machine provides the real hardware.\n- A hypervisor creates and manages the virtual machines.\n- Each VM gets its own operating system and virtual hardware view.\n- Many VMs can share one physical host while staying isolated from one another.\n\nUseful ideas:\n\n- Type 1 hypervisors run directly on hardware.\n- Type 2 hypervisors run on top of an existing operating system.\n- A VM can be made to look like standard hardware so it is easier to test software safely.\n\nSources:\n\n- Microsoft Hyper-V overview: [Hyper-V virtualization in Windows Server and Windows](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-overview)\n- Microsoft terminology and VM generations: [Hyper-V Features and Terminology Overview](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/features-terminology)\n- Microsoft Hyper-V architecture overview: [Hyper-V architecture](https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/role/hyper-v-server/architecture)\n\nChecklist:\n\n- [x] Write the first original virtualization page.\n- [x] Define host, hypervisor, and VM in simple terms.\n- [x] Add authoritative source links.\n- [ ] Add a VM versus physical machine visual.\n- [x] Link the virtualization flash-card lab.\n\nPractice\n\n- [Review Visual Cards](../../app/index.html#module=flash)\n"
    },
    {
      "order": 9,
      "sequence_id": "CS-009",
      "group": "Virtualization and cloud sequence",
      "topic": "Cloud computing",
      "slug": "cloud-computing",
      "material_path": "materials/course-sequence/cloud-computing.md",
      "comptia_area": "Virtualization and Cloud Computing",
      "route_id": "MAP-003",
      "app_module": "flash",
      "practice_action": "Review Visual Cards",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Cloud Computing\n\n## What\n\nCloud computing is the delivery of computing services over the internet.\n\nThose services can include servers, storage, networking, software, and other managed resources.\n\n## Why\n\nLearners need a simple cloud model because A+ questions often compare cloud services with local hardware and ask what the cloud is good for.\n\nIt also helps explain why a company might rent services instead of buying and maintaining everything itself.\n\n## How\n\n- Think of the cloud as rented computing power and storage.\n- The provider owns and manages the remote infrastructure.\n- The customer uses only the services it needs.\n- Common service models are IaaS, PaaS, and SaaS.\n- Common deployment models are public cloud, private cloud, and hybrid cloud.\n\nExamples:\n\n- IaaS gives you more control over servers, storage, and networking.\n- PaaS gives you a managed platform for building and deploying apps.\n- SaaS gives you a finished application delivered as a service.\n\nSources:\n\n- Microsoft Azure cloud computing definition: [What Is Cloud Computing?](https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-cloud-computing/)\n- Google Cloud cloud computing definition and service models: [What is Cloud Computing?](https://cloud.google.com/learn/what-is-cloud-computing)\n\nChecklist:\n\n- [x] Write the first original cloud-computing page.\n- [x] Define cloud, service models, and deployment models in plain language.\n- [x] Add authoritative source links.\n- [ ] Add a cloud-service comparison card.\n- [x] Link the cloud flash-card lab.\n\nPractice\n\n- [Review Visual Cards](../../app/index.html#module=flash)\n"
    },
    {
      "order": 10,
      "sequence_id": "CS-010",
      "group": "Networking sequence",
      "topic": "Networking basics",
      "slug": "networking-basics",
      "material_path": "materials/course-sequence/networking-basics.md",
      "comptia_area": "Networking",
      "route_id": "MAP-002",
      "app_module": "topology",
      "practice_action": "Trace Network Path",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Networking Basics\n\n## What\n\nNetworking basics is the set of ideas that explain how devices talk to each other and to the internet.\n\nAt this level, the learner should know the roles of switches, routers, access points, and DNS.\n\n## Why\n\nThis is the foundation for the networking part of A+.\n\nIf the learner understands the role of each device, later troubleshooting steps stop feeling random.\n\n## How\n\n- A switch connects devices inside the local network.\n- A router connects networks and usually links the local network to the internet.\n- An access point gives wireless devices a way onto the network.\n- DNS turns human-friendly names into addresses computers can use.\n\nUseful framing:\n\n- Switch = local device traffic.\n- Router = between networks.\n- Access point = wireless entry.\n- DNS = name lookup.\n\nSources:\n\n- Cisco overview of switches, routers, and access points: [Networking basics](https://www.cisco.com/site/us/en/learn/topics/small-business/networking-basics.html)\n- Cisco explanation of DNS in network communications: [Understand DNS](https://www.cisco.com/c/en/us/support/docs/security/umbrella/225283-understand-dns.html)\n\nChecklist:\n\n- [x] Write the first original networking page.\n- [x] Define switch, router, access point, and DNS in plain language.\n- [x] Add authoritative source links.\n- [ ] Add a network-role visual.\n- [x] Link the network path activity.\n\nPractice\n\n- [Trace Network Path](../../app/index.html#module=topology)\n"
    },
    {
      "order": 11,
      "sequence_id": "CS-011",
      "group": "Networking sequence",
      "topic": "Wireless networks",
      "slug": "wireless-networks",
      "material_path": "materials/course-sequence/wireless-networks.md",
      "comptia_area": "Networking",
      "route_id": "MAP-002",
      "app_module": "topology",
      "practice_action": "Trace Network Path",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Wireless Networks\n\n## What\n\nWireless networks let devices connect without a cable.\n\nIn practice, most learners meet this as Wi-Fi on a home, school, or office network.\n\n## Why\n\nWireless is everywhere, so A+ learners need to understand both the convenience and the extra risk it brings.\n\nThat makes wireless one of the most practical networking topics to learn early.\n\n## How\n\n- A wireless access point or wireless router provides radio coverage.\n- A Wi-Fi client connects from within range.\n- Strong passwords and encryption matter because the signal travels through the air.\n- Wireless is convenient, but the device still depends on the same network ideas as wired networking.\n\nUseful framing:\n\n- Wired and wireless are both network access.\n- Wi-Fi is the common WLAN technology.\n- Good security settings matter more because nearby devices can attempt to join.\n\nSources:\n\n- Cisco explanation of Wi-Fi networks: [What is a Wi-Fi network?](https://www.cisco.com/site/us/en/learn/topics/networking/what-is-a-wi-fi-network.html)\n- Cisco Wi-Fi security overview: [What is Wi-Fi Security?](https://www.cisco.com/c/en/us/products/wireless/what-is-wi-fi-security.html)\n\nChecklist:\n\n- [x] Write the first original wireless page.\n- [x] Define Wi-Fi and wireless access in plain language.\n- [x] Add authoritative source links.\n- [ ] Add a wireless-versus-wired visual.\n- [x] Link the wireless practice activity.\n\nPractice\n\n- [Trace Network Path](../../app/index.html#module=topology)\n"
    },
    {
      "order": 12,
      "sequence_id": "CS-012",
      "group": "Networking sequence",
      "topic": "Internet connections",
      "slug": "internet-connections",
      "material_path": "materials/course-sequence/internet-connections.md",
      "comptia_area": "Networking",
      "route_id": "MAP-002",
      "app_module": "topology",
      "practice_action": "Trace Network Path",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Internet Connections\n\n## What\n\nInternet connections are the paths that link a local network to online services.\n\nThis usually means the connection from the device, through the local network gear, to the service provider and then to the public internet.\n\n## Why\n\nLearners need to know where the connection actually starts and stops.\n\nThat keeps troubleshooting focused on the real weak point instead of random guesswork.\n\n## How\n\n- A device connects to the local network first.\n- A router or gateway is usually the first handoff point to the wider internet.\n- DNS helps turn a site name into an IP address.\n- If the internet is down, the learner should check the local path first, then the provider side.\n\nUseful framing:\n\n- Local network problems happen before the router can pass traffic out.\n- DNS problems can make the internet look broken even when the link is up.\n- A working connection still depends on a valid IP address, default gateway, and DNS setup.\n\nSources:\n\n- Microsoft overview of IP addressing and subnetting basics: [TCP/IP addressing and subnetting](https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/tcpip-addressing-and-subnetting)\n- Microsoft DNS overview: [DNS Overview](https://learn.microsoft.com/en-us/windows/win32/dns/dns-overview)\n- Cisco DNS explainer for network users: [Understand DNS](https://www.cisco.com/c/en/us/support/docs/security/umbrella/225283-understand-dns.html)\n\nChecklist:\n\n- [x] Write the first original internet-connections page.\n- [x] Explain the local-to-internet path in plain language.\n- [x] Add authoritative source links.\n- [ ] Add a connection-path visual.\n- [x] Link the internet-connection practice activity.\n\nPractice\n\n- [Trace Network Path](../../app/index.html#module=topology)\n"
    },
    {
      "order": 13,
      "sequence_id": "CS-013",
      "group": "Networking sequence",
      "topic": "Network addressing and communication",
      "slug": "network-addressing-and-communication",
      "material_path": "materials/course-sequence/network-addressing-and-communication.md",
      "comptia_area": "Networking",
      "route_id": "MAP-002",
      "app_module": "topology",
      "practice_action": "Trace Network Path",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Network Addressing And Communication\n\n## What\n\nNetwork addressing tells devices where they are on the network.\n\nCommunication is the set of rules and steps that let devices exchange data using those addresses.\n\n## Why\n\nThis is the part of networking that explains why IP addresses, subnet masks, and gateways matter.\n\nIt also explains why a device can have a connection but still not reach the destination it needs.\n\n## How\n\n- An IP address identifies a host on a TCP/IP network.\n- A subnet mask separates the network part from the host part.\n- A default gateway is the path out of the local network.\n- DNS resolves names into IP addresses so the communication can begin.\n\nUseful framing:\n\n- IP address = where the device is.\n- Subnet mask = what counts as local.\n- Default gateway = exit path.\n- DNS = name-to-number lookup.\n\nSources:\n\n- Microsoft explanation of TCP/IP addressing and subnetting: [TCP/IP addressing and subnetting](https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/tcpip-addressing-and-subnetting)\n- Microsoft DNS overview: [DNS Overview](https://learn.microsoft.com/en-us/windows/win32/dns/dns-overview)\n\nChecklist:\n\n- [x] Write the first original addressing page.\n- [x] Define IP, subnet mask, gateway, and DNS in plain language.\n- [x] Add authoritative source links.\n- [ ] Add an IP-versus-subnet visual.\n- [x] Link the addressing and communication practice activity.\n\nPractice\n\n- [Trace Network Path](../../app/index.html#module=topology)\n"
    },
    {
      "order": 14,
      "sequence_id": "CS-014",
      "group": "Networking sequence",
      "topic": "Network configurations",
      "slug": "network-configurations",
      "material_path": "materials/course-sequence/network-configurations.md",
      "comptia_area": "Networking",
      "route_id": "MAP-002",
      "app_module": "topology",
      "practice_action": "Trace Network Path",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Network Configurations\n\n## What\n\nNetwork configuration is the set of settings that lets a device join and use a network.\n\nThat usually includes the IP address, subnet mask, default gateway, DNS servers, and sometimes DHCP behavior.\n\n## Why\n\nThis is one of the most practical A+ networking topics because a device can be connected and still have the wrong settings.\n\nIf the configuration is off, the network may look broken even when the cable or Wi-Fi link is fine.\n\n## How\n\n- Use `ipconfig` or the network settings panel to inspect current values.\n- Check whether the address was assigned manually or by DHCP.\n- Confirm the default gateway points to the device that connects the local network outward.\n- Confirm DNS is set so names can resolve correctly.\n\nUseful framing:\n\n- DHCP usually hands out configuration automatically.\n- Static settings are entered by hand.\n- `ipconfig /all` shows the core configuration values on Windows.\n\nSources:\n\n- Microsoft `ipconfig` command reference: [ipconfig](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ipconfig?view=windows-server-2019)\n- Microsoft guide to changing the IP address of a network adapter: [How to change the IP address of a network adapter](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/change-ip-address-network-adapter)\n- Cisco DHCP and DNS service notes: [DHCP and DDNS](https://www.cisco.com/c/en/us/td/docs/security/secure-firewall/management-center/device-config/720/management-center-device-config-72/interfaces-settings-dhcp-ddns.pdf)\n\nChecklist:\n\n- [x] Write the first original network-configuration page.\n- [x] Explain DHCP, static addressing, gateway, and DNS.\n- [x] Add authoritative source links.\n- [ ] Add a config-values visual.\n- [x] Link the configuration-check practice activity.\n\nPractice\n\n- [Trace Network Path](../../app/index.html#module=topology)\n"
    },
    {
      "order": 15,
      "sequence_id": "CS-015",
      "group": "Networking sequence",
      "topic": "Network servers and services",
      "slug": "network-servers-and-services",
      "material_path": "materials/course-sequence/network-servers-and-services.md",
      "comptia_area": "Networking",
      "route_id": "MAP-002",
      "app_module": "topology",
      "practice_action": "Trace Network Path",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Network Servers And Services\n\n## What\n\nNetwork servers and services are the shared helpers that make a network useful.\n\nCommon examples include DHCP, DNS, file sharing, and other services that users rely on every day without seeing the server itself.\n\n## Why\n\nThis topic helps the learner understand that a network is more than cables and addresses.\n\nThe network also depends on services that hand out settings, resolve names, and support shared resources.\n\n## How\n\n- DHCP gives clients network settings automatically.\n- DNS helps translate names into addresses.\n- File and resource sharing let people use shared data or devices on a network.\n- A server can host one or many of these jobs.\n\nUseful framing:\n\n- Server = the system providing a service.\n- Service = the capability the client needs.\n- DHCP and DNS are core support services in many small and large networks.\n\nSources:\n\n- Microsoft `ipconfig` documentation showing DHCP and DNS refresh behavior: [ipconfig](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ipconfig?view=windows-server-2019)\n- Cisco DHCP and DNS service notes: [DHCP and DDNS](https://www.cisco.com/c/en/us/td/docs/security/secure-firewall/management-center/device-config/720/management-center-device-config-72/interfaces-settings-dhcp-ddns.pdf)\n- Cisco host services and applications overview: [Implementing Host Services and Applications](https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-6/b-ip-addresses-cg-asr9000-76x/Implementing-host-services-and-applications.pdf)\n\nChecklist:\n\n- [x] Write the first original network-servers page.\n- [x] Explain DHCP, DNS, and shared services in plain language.\n- [x] Add authoritative source links.\n- [ ] Add a services-and-clients visual.\n- [x] Link the network-services practice activity.\n\nPractice\n\n- [Trace Network Path](../../app/index.html#module=topology)\n"
    },
    {
      "order": 16,
      "sequence_id": "CS-016",
      "group": "Mobile and laptop sequence",
      "topic": "Laptops and mobile devices",
      "slug": "laptops-and-mobile-devices",
      "material_path": "materials/course-sequence/laptops-and-mobile-devices.md",
      "comptia_area": "Mobile Devices",
      "route_id": "MAP-004",
      "app_module": "laptop",
      "practice_action": "Open Laptop Hardware",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Laptops And Mobile Devices\n\n## What\n\nLaptops and mobile devices are portable computers.\n\nThat group includes laptops, tablets, and phones that people carry, dock, sync, and use on the move.\n\n## Why\n\nThis topic matters because A+ learners need to recognise the differences in form factor, power use, connectivity, and user expectations.\n\nPortable devices often blur together in everyday language, but the hardware and support needs are not the same.\n\n## How\n\n- A laptop is a full computer in a portable form.\n- A tablet is usually touch-first and lighter on physical ports.\n- A phone or tablet may rely heavily on cloud sync and wireless services.\n- Device setup often includes account sign-in, syncing, backup, and security settings.\n\nUseful framing:\n\n- Laptop = portable workstation.\n- Tablet = touch-focused portable device.\n- Phone = communication-first portable device.\n- Sync and backup are part of normal support, not extra features.\n\nSources:\n\n- Microsoft overview of mobile devices and Exchange ActiveSync support: [Mobile devices](https://learn.microsoft.com/en-us/exchange/clients/exchange-activesync/mobile-devices)\n- Apple iPad sync and cloud features: [Use iCloud on iPad](https://support.apple.com/en-euro/guide/ipad/ipad2161498f/ipados)\n- Apple iPad setup and feature overview: [iPad User Guide](https://support.apple.com/en-mide/guide/ipad/ipadc51cb375/ipados)\n\nChecklist:\n\n- [x] Write the first original laptops-and-mobile-devices page.\n- [x] Define portable device types in plain language.\n- [x] Add authoritative source links.\n- [ ] Add a portable-device comparison visual.\n- [x] Link the mobile-device practice activity.\n\nPractice\n\n- [Open Laptop Hardware](../../app/index.html#module=laptop)\n"
    },
    {
      "order": 17,
      "sequence_id": "CS-017",
      "group": "Mobile and laptop sequence",
      "topic": "Mobile applications",
      "slug": "mobile-applications",
      "material_path": "materials/course-sequence/mobile-applications.md",
      "comptia_area": "Mobile Devices",
      "route_id": "MAP-004",
      "app_module": "laptop",
      "practice_action": "Open Laptop Hardware",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Mobile Applications\n\n## What\n\nMobile applications are the software apps people install and use on phones and tablets.\n\nThese apps often rely on the app store, operating system permissions, account sync, and device security settings.\n\n## Why\n\nThis topic helps the learner understand that apps on mobile devices are controlled differently from desktop apps.\n\nThat includes installation rules, update paths, permissions, and the way data syncs across devices.\n\n## How\n\n- Install apps from the device’s official store or managed app source.\n- Review permissions before allowing camera, location, contacts, or notifications access.\n- Keep apps updated so they stay compatible and secure.\n- Use account sync when the app stores data in the cloud.\n\nUseful framing:\n\n- App stores help with compatibility and safety checks.\n- Permissions should match the app’s real need.\n- Mobile apps can support work, messaging, photos, notes, and security tasks.\n\nSources:\n\n- Android features and app compatibility overview: [Android Features & Operating System Consistency](https://www.android.com/articles/android-features-and-apps/)\n- Android mobile device security overview: [Mobile device security and data protection](https://www.android.com/intl/en_us/safety/)\n- Samsung mobile security overview: [Galaxy Security](https://www.samsung.com/us/security/)\n\nChecklist:\n\n- [x] Write the first original mobile-applications page.\n- [x] Define mobile app behavior in plain language.\n- [x] Add authoritative source links.\n- [ ] Add a permissions-and-store visual.\n- [x] Link the mobile-app practice activity.\n\nPractice\n\n- [Open Laptop Hardware](../../app/index.html#module=laptop)\n"
    },
    {
      "order": 18,
      "sequence_id": "CS-018",
      "group": "Mobile and laptop sequence",
      "topic": "Laptop hardware",
      "slug": "laptop-hardware",
      "material_path": "materials/course-sequence/laptop-hardware.md",
      "comptia_area": "Mobile Devices",
      "route_id": "MAP-004",
      "app_module": "laptop",
      "practice_action": "Open Laptop Hardware",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Laptop Hardware\n\nWhat\n\nLaptop hardware is the set of parts packed into a portable computer: display, keyboard, touchpad, ports, battery, storage, memory, cooling, wireless card, and system board. The support goal is to identify the part, understand what it does, and avoid treating a laptop like an easy-open desktop.\n\nWhy\n\nLaptops are compact, fragile, and model-specific. A learner should recognize the visible parts first, then understand which internal parts are common service points and which ones usually need a manual, warranty process, or experienced technician.\n\nHow\n\nRead the laptop in layers:\n\n1. Outside: ports, webcam, keyboard, touchpad, display, speakers, LEDs, charger.\n2. Access panels: storage, memory, battery, wireless card, where the model allows it.\n3. Internal view: cooling fan, heatsink, motherboard, ribbon cables, antennas.\n4. Service decision: reseat, replace, update, document, or escalate.\n\nUseful support clues:\n\n- USB-C can carry power, data, display, or docking, but the exact features depend on the model.\n- SO-DIMM RAM is the small laptop memory format when memory is not soldered.\n- M.2 SSDs are small storage cards mounted directly to the motherboard.\n- Wi-Fi and Bluetooth may share a small wireless card and antenna leads.\n- Display, keyboard, and touchpad repairs often involve ribbon cables and model-specific steps.\n\n```mermaid\nflowchart TD\n  Laptop[\"Laptop\"] --> External[\"External parts\"]\n  Laptop --> Internal[\"Internal parts\"]\n  Laptop --> Service[\"Service decision\"]\n\n  External --> Ports[\"Ports and LEDs\"]\n  External --> Input[\"Keyboard and touchpad\"]\n  External --> Display[\"Display, webcam, microphone\"]\n\n  Internal --> Memory[\"SO-DIMM RAM\"]\n  Internal --> Storage[\"M.2 or 2.5-inch storage\"]\n  Internal --> Wireless[\"Wi-Fi / Bluetooth card\"]\n  Internal --> Cooling[\"Fan and heatsink\"]\n  Internal --> Board[\"Motherboard and cables\"]\n\n  Service --> Manual[\"Check model manual\"]\n  Service --> Safe[\"Use ESD and battery safety\"]\n  Service --> Escalate[\"Escalate fragile repairs\"]\n```\n\nPractice\n\n- [Open Laptop Hardware](../../app/index.html#module=laptop)\n\nSources:\n\n- [CompTIA A+ Core 1 and 2 V15](https://www.comptia.org/en-us/certifications/a/core-1-and-2-v15/)\n- [Dell: A Basic Guide to Identifying the Main Parts of a Laptop](https://www.dell.com/support/kbdoc/en-us/000139511/a-basic-guide-to-identifying-the-major-components-of-a-laptop-system)\n- [HP Support: Components](https://support.hp.com/us-en/document/ish_6508673-6356388-16)\n\nChecklist:\n\n- [x] Define common laptop external parts.\n- [x] Define common laptop internal parts.\n- [x] Separate identification from service decision.\n- [x] Link the laptop hardware app module.\n"
    },
    {
      "order": 19,
      "sequence_id": "CS-019",
      "group": "Printer sequence",
      "topic": "Printers and MFDs",
      "slug": "printers-and-mfds",
      "material_path": "materials/course-sequence/printers-and-mfds.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Printers And MFDs\n\nWhat\n\nPrinters turn digital pages into paper. An MFD, or multifunction device, combines printing with one or more of scan, copy, and fax. In support work, the first job is usually to identify the device type, how it connects, and whether the problem is paper, power, network, driver, or consumables.\n\nWhy\n\nThis topic gives the learner a practical view of office printing without turning it into a vendor brochure. It also helps connect the hardware view to Windows troubleshooting, because many printer problems are connection or driver problems rather than \"printer is broken\" problems.\n\nHow\n\nStart with the basics:\n\n- Check whether the device is inkjet or laser.\n- Check whether it is single-function or multifunction.\n- Check whether it is USB, Ethernet, Wi-Fi, or shared over a print server.\n- Check common consumables like toner, ink, paper, and waste containers.\n- Check status lights, display messages, and print queue errors.\n\nIn a simple help desk flow, we usually think:\n\n1. Power and cable.\n2. Paper and consumables.\n3. Queue and driver.\n4. Network or sharing.\n5. Restart or reinstall if needed.\n\nSources\n\n- [Microsoft Learn: Printer isn't responding](https://learn.microsoft.com/en-us/troubleshoot/windows-server/printing/printer-not-responding)\n- [Microsoft Learn: Printing overview](https://learn.microsoft.com/en-us/troubleshoot/windows-server/printing/printing-overview)\n- [HP: Printer buying guide](https://www.hp.com/us-en/shop/tech-takes/printer-buying-guide?pStoreID=hp_education%27%5B0%5D)\n- [Canon: Printers](https://www.usa.canon.com/shop/printers)\n- [Brother: Inkjet vs Laser Printers](https://www.brother-usa.com/inkjet-vs-laser-printers)\n\nChecklist:\n\n- [x] Define printer vs MFD.\n- [x] Note common connection types.\n- [x] Note common consumables and status checks.\n- [x] Link to official support and product sources.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 20,
      "sequence_id": "CS-020",
      "group": "Printer sequence",
      "topic": "Printer types",
      "slug": "printer-types",
      "material_path": "materials/course-sequence/printer-types.md",
      "comptia_area": "Hardware",
      "route_id": "MAP-001",
      "app_module": "drag",
      "practice_action": "Start Connector Match",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Printer Types\n\nWhat\n\nPrinter types usually break down by print technology and feature set. The big split is inkjet versus laser. A second split is single-function versus multifunction. For the learner, the important thing is not the brand name, but what the device is best at and what it tends to cost to run.\n\nWhy\n\nThis topic helps the learner match the right printer to the job. It also makes troubleshooting easier, because inkjet and laser devices fail in different ways and use different consumables.\n\nHow\n\nUse these comparisons:\n\n- Inkjet: good for photos, mixed color work, and lower-volume home or small office use.\n- Laser: good for fast text printing, higher-volume document work, and lower per-page cost in many office setups.\n- Single-function: prints only.\n- Multifunction: prints plus scan, copy, and sometimes fax.\n\nUseful support clues:\n\n- Inkjet problems often involve clogged nozzles, dried ink, or cartridge issues.\n- Laser problems often involve toner, drums, fusers, or paper feed problems.\n- MFDs add extra paths for scanning and copying, so the issue may not be printing at all.\n\nSources\n\n- [HP: What Types of Printers are Available Today?](https://www.hp.com/us-en/shop/tech-takes/what-types-of-printers-are-available)\n- [HP: Laser Printer vs Inkjet](https://www.hp.com/gb-en/shop/tech-takes/laser-printer-vs-inkjet?pStoreID=hp_education%5C)\n- [Brother: Inkjet vs Laser Printers](https://www.brother-usa.com/inkjet-vs-laser-printers)\n- [Canon: Printers](https://www.usa.canon.com/shop/printers)\n\nChecklist:\n\n- [x] Distinguish inkjet and laser.\n- [x] Distinguish single-function and multifunction.\n- [x] Note common support symptoms by type.\n- [x] Link to official printer comparison sources.\n\nPractice\n\n- [Start Connector Match](../../app/index.html#module=drag)\n"
    },
    {
      "order": 21,
      "sequence_id": "CS-021",
      "group": "Troubleshooting sequence",
      "topic": "Troubleshooting methodology",
      "slug": "troubleshooting-methodology",
      "material_path": "materials/course-sequence/troubleshooting-methodology.md",
      "comptia_area": "Hardware and Networking Troubleshooting",
      "route_id": "MAP-005",
      "app_module": "tickets",
      "practice_action": "Open Ticket Board",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Troubleshooting Methodology\n\nWhat\n\nTroubleshooting methodology is the repeatable way we solve a problem without guessing. In A+ terms, the goal is to identify the symptom, narrow the cause, test one change at a time, and confirm the fix.\n\nWhy\n\nThis is the core skill behind almost every support task. A steady process saves time, reduces repeat work, and stops learners from jumping straight to random fixes.\n\nHow\n\nA simple support flow looks like this:\n\n1. Identify the problem.\n2. Gather information and duplicate the issue.\n3. Decide what is most likely causing it.\n4. Test one likely fix.\n5. Verify the result.\n6. Document what happened.\n\nHelpful habits:\n\n- Ask what changed.\n- Check the obvious first.\n- Change one thing at a time.\n- Reproduce the issue after each change.\n- Keep notes so the next person does not start from zero.\n\nSources\n\n- [Microsoft Learn: Troubleshoot problems in Windows](https://support.microsoft.com/windows/troubleshoot-problems-in-windows-1f6fe8d9-4cce-4f4f-bc42-20a1d3d21d2a)\n- [Microsoft Learn: Run the troubleshooter for devices](https://support.microsoft.com/windows/fix-printer-problems-in-windows-74f2bcee-0c34-d9ee-2f3c-efaa90af7c4c)\n- [Microsoft Support: Troubleshoot Windows and device performance issues](https://support.microsoft.com/windows/troubleshoot-windows-and-device-performance-issues-67e32df7-52f6-0e0d-2b94-7d3b87d6e4f0)\n\nChecklist:\n\n- [x] Define the troubleshooting goal.\n- [x] Keep one change at a time.\n- [x] Verify the fix before moving on.\n- [x] Record the result.\n\nPractice\n\n- [Open Ticket Board](../../app/index.html#module=tickets)\n"
    },
    {
      "order": 22,
      "sequence_id": "CS-022",
      "group": "Troubleshooting sequence",
      "topic": "Troubleshooting hardware issues",
      "slug": "troubleshooting-hardware-issues",
      "material_path": "materials/course-sequence/troubleshooting-hardware-issues.md",
      "comptia_area": "Hardware and Networking Troubleshooting",
      "route_id": "MAP-005",
      "app_module": "tickets",
      "practice_action": "Open Ticket Board",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Troubleshooting Hardware Issues\n\nWhat\n\nHardware troubleshooting means checking physical parts and their connections before assuming the whole device has failed. Common examples are power, RAM, storage, display, ports, fans, keyboard, mouse, and printer hardware.\n\nWhy\n\nLearners need a practical way to sort out \"does not power on\" from \"powers on but misbehaves\". The answer changes depending on whether the issue is cable, component, driver, or a deeper failure.\n\nHow\n\nUse a simple hardware checklist:\n\n- Confirm power source and cable.\n- Watch for lights, fans, beeps, or display output.\n- Reseat obvious components when safe to do so.\n- Try a known-good cable, display, or peripheral.\n- Check Device Manager and built-in diagnostics if the system starts.\n- Replace the smallest likely faulty part first.\n\nCommon examples:\n\n- No power: outlet, PSU, battery, charger, or power button.\n- No video: cable, monitor, port, or graphics adapter.\n- Random shutdowns: heat, fan, or power instability.\n- Missing device: bad cable, disabled port, driver, or failed hardware.\n\nSources\n\n- [Microsoft Learn: Windows hardware device troubleshooting](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/device-troubleshooting)\n- [Microsoft Support: Fix sound or audio problems in Windows](https://support.microsoft.com/windows/fix-sound-or-audio-problems-in-windows-73025246-b61d-bcac-535e-530328c089d4)\n- [Microsoft Support: Fix printer problems in Windows](https://support.microsoft.com/windows/fix-printer-problems-in-windows-74f2bcee-0c34-d9ee-2f3c-efaa90af7c4c)\n\nChecklist:\n\n- [x] Check power and cables first.\n- [x] Use known-good swap tests where possible.\n- [x] Separate no-power from no-video problems.\n- [x] Verify and document the fix.\n\nPractice\n\n- [Open Ticket Board](../../app/index.html#module=tickets)\n"
    },
    {
      "order": 23,
      "sequence_id": "CS-023",
      "group": "Troubleshooting sequence",
      "topic": "Troubleshooting storage devices",
      "slug": "troubleshooting-storage-devices",
      "material_path": "materials/course-sequence/troubleshooting-storage-devices.md",
      "comptia_area": "Hardware and Networking Troubleshooting",
      "route_id": "MAP-005",
      "app_module": "tickets",
      "practice_action": "Open Ticket Board",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Troubleshooting Storage Devices\n\nWhat\n\nStorage troubleshooting is the work of finding out why a drive, SSD, USB device, or storage path is slow, missing, corrupted, or unreadable. The problem may be the disk itself, the cable, the port, the firmware, the file system, or the storage configuration.\n\nWhy\n\nThis topic matters because storage issues often look like \"my files vanished\" when the root cause is actually much smaller. A learner who can isolate the storage layer quickly can prevent data loss and avoid unnecessary re-installs.\n\nHow\n\nStart with these checks:\n\n- Confirm the device is detected in the OS.\n- Check power, cable, and port.\n- Look for bad sectors, SMART warnings, or capacity errors.\n- Try a known-good cable or port.\n- Update drivers and firmware where appropriate.\n- Check whether the file system needs repair or the volume needs to be reassigned.\n\nTypical signs:\n\n- Slow boot or file access.\n- Drive not listed in File Explorer or Disk Management.\n- USB storage disconnecting and reconnecting.\n- Clicking, grinding, or repeated spin-up sounds on spinning disks.\n- Low storage warnings or failed updates because the disk is full.\n\nSources\n\n- [Microsoft Support: Storage settings in Windows](https://support.microsoft.com/en-us/windows/storage-settings-in-windows-5bc98443-0711-8038-4621-6a18ddc904f2)\n- [Microsoft Learn: Error when you access a USB storage device](https://learn.microsoft.com/en-us/troubleshoot/windows-client/setup-upgrade-and-drivers/error-when-you-access-usb-storage-device)\n- [Microsoft Learn: Troubleshoot storage issues in Hyper-V and Windows Server failover clusters](https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/storage-issues-in-hyper-v-and-windows-server-failover-clusters)\n\nChecklist:\n\n- [x] Confirm detection first.\n- [x] Swap cable or port if possible.\n- [x] Check storage health and file system.\n- [x] Update firmware or drivers when relevant.\n\nPractice\n\n- [Open Ticket Board](../../app/index.html#module=tickets)\n"
    },
    {
      "order": 24,
      "sequence_id": "CS-024",
      "group": "Troubleshooting sequence",
      "topic": "Troubleshooting video issues",
      "slug": "troubleshooting-video-issues",
      "material_path": "materials/course-sequence/troubleshooting-video-issues.md",
      "comptia_area": "Hardware and Networking Troubleshooting",
      "route_id": "MAP-005",
      "app_module": "tickets",
      "practice_action": "Open Ticket Board",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Troubleshooting Video Issues\n\nWhat\n\nVideo troubleshooting covers blank screens, flickering, poor playback, and display connection issues. The most common causes are cable problems, the wrong display mode, refresh-rate mismatch, or a graphics driver issue.\n\nWhy\n\nVideo faults are stressful because they block the whole interface, not just one app. Learners need a simple way to separate cable and monitor issues from driver and configuration issues.\n\nHow\n\nUse a short checklist:\n\n- Confirm the monitor has power.\n- Check the cable and input source.\n- Try another video port or cable.\n- Reset or update the graphics driver.\n- Check display mode and refresh rate.\n- Test with another monitor if available.\n\nTypical signs:\n\n- Black screen at startup or after login.\n- Flickering desktop or flickering taskbar.\n- Output appears on the wrong display.\n- Poor video playback or stuttering.\n- External monitor not detected.\n\nSources\n\n- [Microsoft Support: Troubleshoot screen flickering in Windows](https://support.microsoft.com/en-us/windows/fix-screen-flickering-in-windows-f96b545d-a34c-40da-9115-378f78fbbbbf)\n- [Microsoft Support: Troubleshooting blank screens in Windows](https://support.microsoft.com/en-us/windows/troubleshooting-black-or-blank-screens-in-windows-51ef7b96-47cb-b454-fcab-fac643784457)\n- [Microsoft Support: Troubleshoot external monitor connections in Windows](https://support.microsoft.com/en-us/windows/troubleshoot-external-monitor-connections-in-windows-5b46f4a4-9634-06bb-7622-f960facdfd49)\n- [Microsoft Support: Video playback settings in Windows](https://support.microsoft.com/en-gb/windows/troubleshooting-poor-video-playback-339d01fc-4d69-f720-1096-9d93bc5ea410)\n\nChecklist:\n\n- [x] Check monitor power and cable.\n- [x] Distinguish blank screen from flicker.\n- [x] Try display and driver changes.\n- [x] Verify playback or output on another screen.\n\nPractice\n\n- [Open Ticket Board](../../app/index.html#module=tickets)\n"
    },
    {
      "order": 25,
      "sequence_id": "CS-025",
      "group": "Troubleshooting sequence",
      "topic": "Troubleshooting networks",
      "slug": "troubleshooting-networks",
      "material_path": "materials/course-sequence/troubleshooting-networks.md",
      "comptia_area": "Hardware and Networking Troubleshooting",
      "route_id": "MAP-005",
      "app_module": "tickets",
      "practice_action": "Open Ticket Board",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Troubleshooting Networks\n\nWhat\n\nNetwork troubleshooting means finding out why a device cannot connect, cannot reach the internet, or cannot reach a specific service. The problem might be Wi-Fi, Ethernet, DNS, IP addressing, a router, a firewall, or a service outage.\n\nWhy\n\nThis topic matters because many \"network\" failures are really connection, address, or name-resolution problems. A learner who can sort those layers quickly can avoid chasing the wrong fix.\n\nHow\n\nStart with the visible checks:\n\n- Confirm the device is connected to the right network.\n- Check Wi-Fi, cable, port, and airplane mode or adapter state.\n- Test another site, then another device.\n- Check IP address, gateway, and DNS.\n- Reset the adapter or network stack if needed.\n- Restart the router or access point if the issue is local.\n\nTypical signs:\n\n- Connected but no internet.\n- No network icon or limited connectivity.\n- Slow page loads or only some sites failing.\n- DNS errors.\n- Printer, file share, or app access failing even though Wi-Fi looks fine.\n\nSources\n\n- [Microsoft Support: Fix Wi-Fi connection issues in Windows](https://support.microsoft.com/en-US/windows/fix-network-connection-issues-in-windows-10-166a28c4-14c1-bdb1-473c-09c1571455d8)\n- [Microsoft Support: Essential Network Settings and Tasks in Windows](https://support.microsoft.com/en-us/windows/check-your-network-connection-status-efb4fb41-f751-567a-f60f-aac9114659a5)\n- [Microsoft Support: Windows troubleshooters](https://support.microsoft.com/en-us/windows/use-a-troubleshooter-with-windows-10-cc3cb85b-91d7-7e56-8ce1-db50b4d18d0b)\n\nChecklist:\n\n- [x] Check the active connection first.\n- [x] Separate local network from internet issues.\n- [x] Test IP, DNS, and reachability.\n- [x] Reset or restart only after the basics.\n\nPractice\n\n- [Open Ticket Board](../../app/index.html#module=tickets)\n"
    },
    {
      "order": 26,
      "sequence_id": "CS-026",
      "group": "Troubleshooting sequence",
      "topic": "Troubleshooting mobile devices",
      "slug": "troubleshooting-mobile-devices",
      "material_path": "materials/course-sequence/troubleshooting-mobile-devices.md",
      "comptia_area": "Hardware and Networking Troubleshooting",
      "route_id": "MAP-005",
      "app_module": "tickets",
      "practice_action": "Open Ticket Board",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Troubleshooting Mobile Devices\n\nWhat\n\nMobile device troubleshooting covers phones and tablets that will not charge, will not connect, will not sync, or will not hold a stable connection to Wi-Fi, Bluetooth, or a computer. The issue may be power, settings, account sync, or a bad cable.\n\nWhy\n\nMobile problems often look bigger than they are because the device is small and the user expects everything to \"just work\". A calm checklist helps the learner isolate the issue without jumping into resets too early.\n\nHow\n\nUse this order:\n\n- Check battery, charger, and cable.\n- Check airplane mode, Wi-Fi, Bluetooth, and hotspot settings.\n- Confirm the app or account is signed in.\n- Try another cable, port, or charger.\n- Restart the device and update if needed.\n- Re-pair or re-enroll only after the basics.\n\nTypical signs:\n\n- Not charging or charging slowly.\n- Wi-Fi drops or Bluetooth will not pair.\n- Sync delays for mail, contacts, or files.\n- App connection issues after an update.\n- USB connection works for charging but not data.\n\nSources\n\n- [Microsoft Support: Troubleshoot Bluetooth not connecting in Windows](https://support.microsoft.com/en-us/windows/troubleshoot-bluetooth-not-connecting-in-windows-b91d81ec-5b3c-4bcd-be58-d09a91bb163e)\n- [Microsoft Support: Troubleshooting Phone screen for the Phone Link](https://support.microsoft.com/en-us/topic/troubleshooting-phone-screen-for-the-phone-link-17dd2b5e-02a1-3896-a972-c57e081ace6a)\n- [Apple Training: Apple Device Support Exam Prep Guide](https://training.apple.com/content/dam/appletraining/us/en/2025/documents/Apple%20Device%20Support%20Exam%20Prep%20Guide%20EN.pdf)\n\nChecklist:\n\n- [x] Check battery and cable first.\n- [x] Separate connection, sync, and app problems.\n- [x] Re-pair or reset only after basics.\n- [x] Verify the fix on the original task.\n\nPractice\n\n- [Open Ticket Board](../../app/index.html#module=tickets)\n"
    },
    {
      "order": 27,
      "sequence_id": "CS-027",
      "group": "Troubleshooting sequence",
      "topic": "Troubleshooting printer devices",
      "slug": "troubleshooting-printer-devices",
      "material_path": "materials/course-sequence/troubleshooting-printer-devices.md",
      "comptia_area": "Hardware and Networking Troubleshooting",
      "route_id": "MAP-005",
      "app_module": "tickets",
      "practice_action": "Open Ticket Board",
      "content_status": "source-backed draft",
      "source_status": "source links added",
      "markdown": "# Troubleshooting Printer Devices\n\nWhat\n\nPrinter troubleshooting is the work of finding out why a printer will not print, prints badly, prints slowly, or appears offline. Common causes are paper jams, empty consumables, bad connections, driver issues, queue problems, or a stuck spooler.\n\nWhy\n\nPrinters can look complicated, but most failures are plain and mechanical. The learner benefits from a short checklist that starts with the physical device and then moves inward to drivers and queues.\n\nHow\n\nUse this order:\n\n- Check power, paper, and ink or toner.\n- Clear paper jams and close covers.\n- Check USB, Ethernet, Wi-Fi, or Bluetooth connection.\n- Print a test page.\n- Clear the print queue if jobs are stuck.\n- Update or reinstall the printer driver if needed.\n- Check the printer troubleshooter and manufacturer support if the issue stays.\n\nTypical signs:\n\n- Printer not found or not recognized.\n- Stuck queue or print spooler failure.\n- Offline status or shared printer not reachable.\n- Blank pages, streaks, faded text, or poor alignment.\n- Paper jam or tray feed errors.\n\nSources\n\n- [Microsoft Support: Fix printer connection and printing problems in Windows](https://support.microsoft.com/en-gb/windows/fix-printer-connection-and-printing-problems-in-windows-fb830bff-7702-6349-33cd-9443fe987f73)\n- [Microsoft Support: Fix printer stopped due to paper jam errors in Windows](https://support.microsoft.com/en-us/windows/fix-printer-stopped-due-to-paper-jam-errors-in-windows-06c4cc1d-a8d9-4582-8813-8926285c3ed0)\n- [Microsoft Support: Download and install the latest printer drivers](https://support.microsoft.com/en-us/windows/download-and-install-the-latest-printer-drivers-4ff66446-a2ab-b77f-46f4-a6d3fe4bf661)\n- [Microsoft Support: Windows troubleshooters](https://support.microsoft.com/en-us/windows/use-a-troubleshooter-with-windows-10-cc3cb85b-91d7-7e56-8ce1-db50b4d18d0b)\n\nChecklist:\n\n- [x] Check device basics first.\n- [x] Clear jams and stuck jobs.\n- [x] Test the connection and driver.\n- [x] Use the built-in troubleshooter.\n\nPractice\n\n- [Open Ticket Board](../../app/index.html#module=tickets)\n"
    }
  ]
};
